import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import express from 'express';
import cors from 'cors';
import { offlineApi } from './offline-api.js';

test('offline catalog, original packs and separate source thumbnails are provider-qualified and read-only', async t => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), 'offline-api-'));
    const favorites = path.join(root, 'favorites');
    const sources = path.join(root, 'sources');
    await fs.mkdir(favorites, { recursive: true });
    for (const provider of ['hitomi', 'imhentai']) {
        await fs.writeFile(path.join(favorites, `${provider}.json`), JSON.stringify({ ids: [123, 456] }));
        const dir = path.join(sources, provider, '123');
        await fs.mkdir(dir, { recursive: true });
        await fs.writeFile(path.join(dir, 'info.json'), JSON.stringify({ title_jpn: '日本語', count: provider === 'hitomi' ? 4 : 2 }));
        await fs.writeFile(path.join(dir, `${provider}_123_0010.jpg`), 'second');
        await fs.writeFile(path.join(dir, `${provider}_123_0002.jpg`), 'first');
        await fs.writeFile(path.join(dir, `thumb_${provider}_123_0002.jpg`), 'thumb');
        await fs.writeFile(path.join(dir, `${provider}_123_thumb_0002.jpg`), 't1');
        await fs.writeFile(path.join(dir, `${provider}_123_thumb_0010.jpg`), 't2');
    }
    const app = express(); app.use(cors()); app.use('/offline-api', offlineApi(sources, favorites));
    const server = app.listen(0, '127.0.0.1');
    await new Promise<void>(resolve => server.once('listening', resolve));
    t.after(async () => { await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve())); await fs.rm(root, { recursive: true, force: true }); });
    const address = server.address() as { port: number };
    const base = `http://127.0.0.1:${address.port}/offline-api`;
    const response = await fetch(`${base}/catalog`);
    const catalog = await response.json() as { items: { key: string; title: string; ready: boolean }[] };
    assert.equal(response.headers.get('cache-control'), 'no-store');
    assert.equal(response.headers.get('access-control-allow-origin'), null);
    assert.deepEqual(catalog.items.map((i: { key: string }) => i.key), ['hitomi-123', 'hitomi-456', 'imhentai-123', 'imhentai-456']);
    assert.equal(catalog.items[0].title, '日本語');
    assert.equal(catalog.items[0].ready, true);
    assert.equal(catalog.items[1].ready, false);
    const manifest = await (await fetch(`${base}/hitomi/123/manifest`)).json() as { pages: { size: number; offset: number; url: string }[]; bytes: number; revision: string;
        thumbnails: { kind: string; revision: string; pages: { offset: number; size: number; url: string }[]; bytes: number } };
    assert.deepEqual(manifest.pages.map((p: { size: number; offset: number }) => [p.size, p.offset]), [[5, 0], [6, 5]]);
    assert.equal(manifest.bytes, 11);
    assert.match(manifest.revision, /^[a-f0-9]{24}$/);
    assert.equal(manifest.thumbnails.kind, 'thumbnails');
    assert.equal(manifest.thumbnails.bytes, 4);
    assert.deepEqual(manifest.thumbnails.pages.map(p => [p.offset, p.size]), [[0, 2], [2, 2]]);
    const thumb = await fetch(`http://127.0.0.1:${address.port}${manifest.thumbnails.pages[0].url}`);
    assert.equal(thumb.headers.get('cache-control'), 'no-store');
    assert.equal(thumb.headers.get('access-control-allow-origin'), null);
    assert.equal(await thumb.text(), 't1');
    await fs.writeFile(path.join(sources, 'hitomi', '123', 'hitomi_123_thumb_0002.jpg'), 'new thumbnail bytes');
    const repaired = await (await fetch(`${base}/hitomi/123/manifest`)).json() as typeof manifest;
    assert.equal(repaired.revision, manifest.revision, 'thumbnail changes must not invalidate existing original packs');
    assert.notEqual(repaired.thumbnails.revision, manifest.thumbnails.revision);
    assert.equal((await fetch(`${base}/hitomi/123/thumbnails/hitomi_123_0002.jpg`)).status, 400);
    assert.equal((await fetch(`${base}/hitomi/123/thumbnails/imhentai_123_thumb_0002.jpg`)).status, 400);
    const image = await fetch(`http://127.0.0.1:${address.port}${manifest.pages[0].url}`);
    assert.equal(image.headers.get('content-type'), 'image/jpeg');
    assert.equal(image.headers.get('access-control-allow-origin'), null);
    assert.equal(await image.text(), 'first');
    assert.equal((await fetch(`${base}/hitomi/123/pages/info.json`)).status, 400);
    assert.equal((await fetch(`${base}/hitomi/123/pages/thumb_hitomi_123_0002.jpg`)).status, 400);
    assert.equal((await fetch(`${base}/imhentai/123/pages/hitomi_123_0002.jpg`)).status, 400);
    assert.equal((await fetch(`${base}/hitomi/123/pages/..%2Finfo.json`)).status, 400);
    assert.equal((await fetch(`${base}/unknown/123/manifest`)).status, 409);
    await fs.writeFile(path.join(sources, 'hitomi', '.downloading-123'), '');
    assert.equal((await fetch(`${base}/hitomi/123/manifest`)).status, 409);
    const old = await (await fetch(`${base}/imhentai/123/manifest`)).json() as { revision: string };
    await fs.writeFile(path.join(sources, 'imhentai', '123', 'imhentai_123_0010.jpg'), 'second changed');
    const changed = await (await fetch(`${base}/imhentai/123/manifest`)).json() as { revision: string };
    assert.notEqual(changed.revision, old.revision);
});
